FROM python:3.7

RUN pip install pylint

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY test_requirements.txt test_requirements.txt
RUN pip install -r test_requirements.txt

RUN mkdir stage

COPY cwoperator stage/cwoperator
COPY test stage/test
COPY .pylintrc stage/.pylintrc

WORKDIR stage

RUN pylint `ls -d */`
