version: "3.0"
services:
  test-coverage:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/work
    working_dir: /work
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        pytest --cov=`pwd` -vv
        coverage xml
        coverage html
        coverage report -m

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/aws
    environment:
      - AWS_DEFAULT_PROFILE
      - AWS_PROFILE=$AWS_DEFAULT_PROFILE
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
      - AWS_CONFIG_FILE=/aws/config
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - AWS_CONSOLE_URL
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_SDK_LOAD_CONFIG=1

  producer:
    build:
      context: sample/producer
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/aws
    environment:
      - AWS_DEFAULT_PROFILE
      - AWS_PROFILE=$AWS_DEFAULT_PROFILE
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
      - AWS_CONFIG_FILE=/aws/config
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - AWS_CONSOLE_URL
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_SDK_LOAD_CONFIG=1
      - QUEUE_NAME=test
