# Default values for cluster-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

replicas: 1
