---
apiVersion: v1
kind: Service
metadata:
  name: cloudwatchalarm-svc
  namespace: amazon-cloudwatch
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloudwatchalarm
    role: operator