
serviceAccount:
  # defaults to k8s-cloudwatch-adapter
  name:

## Labels to be added to the adapter Deployment
##

image:
  pullPolicy: IfNotPresent

## Optional array of imagePullSecrets containing private registry credentials
## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# - name: secretName

## Runtime arguments
args:
  cert-dir: /tmp
  secure-port: 6443
  logtostderr: true
  v: 2

replicas: 1

## Labels to be added to the adapter Deployment
##
labels: {}

## Annotations to be added to the adapter pods
##
podAnnotations: {}

## Labels to be added to the adapter pods
##
podLabels: {}

## Provide a priority class name the Deployment
##
priorityClassName: ""

service:
  ## Labels to be added to the adapter Service
  ##
  labels: {}

  ## Annotations to be added to the adapter Service
  ##
  annotations: {}
